config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "broadcasts#index"
 # get 'exit', to: 'sessions#destroy', as: :logout
  resources :fans
  resources :groups
  resources :broadcasts
  resources :venues
  resources :teams
  resources :events, except: :destroy 
  resources :likes

  get '/search/teams' => 'teams#search'
  get '/delete/events/:id' => 'events#destroy'
  post 'events/:id' => 'events#update'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drunger Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<!--   SCRIPTS LIBRARY
 -->
  
  <script src="//code.jquery.com/jquery-latest.min.js"></script>
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>

<!--   END OF SCRIPTS LIBRARY
 -->  

<!-- FONTS LIBRARY
 --> <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
<!-- END OF FONTS LIBRARY
 -->

<!-- STYLE SHEETS LIBRARY
-->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<!-- END OF STYLE SHEETS LIBRARY
 -->

  </head>

<body>
  <!-- the following is text pasted from guides.railsgirls.com/devise/ for devise login verification -->

  <div class = "navigation">
    

    <!-- the following is for devise login functions to pop up into the nave bar -->
    <p class="navbar-text pull-left">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
      | <%= link_to 'Home', broadcasts_path, :class => 'navbar-link' %>


    <div class="ui-widget">
      <form id="search_bar" method="GET" action="/search/teams">
        <input class ="search_bar_input" type="search" name="search_parameter" placeholder ="search" id="tags" title="Search for your favorite team by name or by city.">
        <input id = "search_bar_button" type="submit">
      </form>
    </div>

  </div>
  <!-- end of devise function edits -->

  <%= yield %>

</body>
</html>